### ISSUE TITLE
Provide migration tool from previous pcfg files to new class names

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/TagEditorCore#233] opened 2016-08-01 20:48 UTC
We changed the class names last week.  This (apparently) broke the hands-on config files.  If this broke existing config files created by users, we need to provide a migration tool to fix them.

**Comment by Beazurt** [comment] 2016-08-11 22:45
We confirmed this was falsely reported right? Is it safe to close this now?

**Comment by becega** [comment] 2016-08-11 22:48
This was not a bug with the classes. The migration mostly forces re links. During the hands on the problem was in the files copied into the usb file. Not sure how the break line got removed between the version of the file and the actual data.

**Closed by becega** 2016-08-11 22:48 UTC
Labels: Bug
