### ISSUE TITLE
Deleting module does not reset module count

### ISSUE THREAD

**Issue by bkindinger** [LabVIEW-DCAF/TagEditorCore#335] opened 2017-07-26 16:05 UTC
If a module is only allowed a single instance, and you remove it, the parent node does not accurate count how many modules are added.

**Comment by pollockm** [comment] 2017-09-15 21:32
Marking as major bug.  If a user adds a scan engine module, then deletes it, they can never add another scan engine module to that target ever again.  This will be a support issue.

**Comment by jacobson3** [comment] 2018-01-30 18:38
It looks like the problem is coming from the RemoveChileFromNode.vi in Engine Parent Editor Node.lvclass. As seen below, the Targets.ConfigurationClassName keeps track of all modules which are used under that target. When an item is removed we search for it in the list of modules and delete it from the array. The problem is simply that the search 1d array is mis-wired into the length input and not the index.

![2018-01-30 12_32_20-pl framework configuration tool lvlib_engine parent editor node lvclass_removech](https://user-images.githubusercontent.com/25009788/35584346-57425c4c-05ba-11e8-9aef-56b04abf104f.png)

**Closed** 2018-01-30 20:44 UTC
Labels: Bug, Major
