### ISSUE TITLE
Add it unit to engine timing source. 

### ISSUE THREAD

**Issue by tannerblair** [LabVIEW-DCAF/TagEditorCore#227] opened 2016-07-01 16:22 UTC

**Comment by Beazurt** [comment] 2016-12-19 19:06
This seems like a duplicate of this issue. The other issue was submitted after, but has more discussion so let's close this one instead.

https://github.com/LabVIEW-DCAF/StandardEngine/issues/56

**Closed by Beazurt** 2016-12-19 19:06 UTC
Labels: Duplicate, Enhancement
